joint_state_publisher:
  ros__parameters:
    publish_default_positions: true
    rate: 30

rplidar_node:
  ros__parameters:
    serial_port: /dev/lidar
    serial_baudrate: 115200
    frame_id: lidar_link
    inverted: false
    angle_compensate: true

bno055_driver:
  ros__parameters:
    port: /dev/imu
    frame_id: imu_link
    frequency: 10.0
    self_manage: True
    # these calibration values need to be determined on a per-device basis.
    calibration/accelerometer_offset: [-7, -34, -47]
    calibration/magnetometer_offset: [275, -193, -104]
    calibration/gyroscope_offset: [-3, -3, -1]
    calibration/accelerometer_radius: 1000
    calibration/magnetometer_radius: 842

connection:
  ros__parameters:
    serial_port: /dev/rover
